### ISSUE TITLE
Add compileJava task (or something) to gradlew for ihmc_ros_java_adapter

### ISSUE THREAD

**Issue by scpeters** [ihmcrobotics/ihmc_ros_core#2]
We are using the `ihmc_ros_java_adapter` inside a docker container, and we noticed that it would resolve dependencies during run-time. We wanted to speed that up but couldn't find a workable task to pass to the `gradlew` script (it has a [buildSourceProject task](https://github.com/ihmcrobotics/ihmc_ros_core/blob/develop/ihmc_ros_java_adapter/build.gradle#L143), but `./gradlew buildSourceProject` always seemed to invoke `runJavaDelegate`, which is more than I wanted). I did find that explicitly skipping the `runJavaDelegate` task was sufficient for my purposes:

```
./gradlew -x runJavaDelegate -PuseLocal=true
```

Perhaps there's a more elegant / clean way to do this?

**Comment by dljsjr** [comment]
From a quick scan it looks like the big failing here is that when I developed this adapter I developed it w/ the assumption that it would only ever be used to run Java apps, hence there not being a mechanism to disable the `runJavaDelegate` task (technically the task isn't getting run, it's getting configured, but the configuration is failing so the build is failing).

I can definitely see the use-cases for a "build" step, containerization being a good example. I'll need to make the script more flexible then add a new task for warming up the environment and downloading artifacts.

**Comment by scpeters** [comment]
I think this has been fixed for `ihmc_valkyrie_ros` in https://github.com/ihmcrobotics/ihmc_valkyrie_ros/commit/5f1c88fb088bd6553636a68a19aee810f00b2e5e

Feel free to close unless you think something more general should happen in the `ihmc_ros_java_adapter` packages.
